guestbook_homepage:
    pattern:  /form
    defaults: { _controller: CreedGuestbookBundle:Default:index }

guestbook_all_messages:
    pattern: /create
    defaults: { _controller: CreedGuestbookBundle:Default:create }
