parameters:
#    creed_guestbook.example.class: Creed\GuestbookBundle\Example

services:
#    creed_guestbook.example:
#        class: %creed_guestbook.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
